In [2]:
import numpy as np

In [5]:
matrix1=[[1,2,3,6,9,7],
        [5,6,7,8,5,7],
         [0,9,7,4,1,3]]
print("matrix1 =", matrix1)

matrix1 = [[1, 2, 3, 6, 9, 7], [5, 6, 7, 8, 5, 7], [0, 9, 7, 4, 1, 3]]


In [7]:
print( matrix1[2][2])

7


In [8]:
print (matrix1[0][1])

2


In [9]:
print (matrix1[1][3])

8


In [10]:
import numpy as np
matrix2= np.array([0,1,2,3,22,4,5])
print([matrix2[1:5]])

[array([ 1,  2,  3, 22])]


In [11]:
matrix3=np.array([[1,2,6,7],
                [3,7,9,6],
                [1,22,3,7]])
print (matrix3)

[[ 1  2  6  7]
 [ 3  7  9  6]
 [ 1 22  3  7]]


In [15]:
print (matrix3 [1][1])

7


Matrix addition


In [6]:
add1=np.array([[2,3,4],[3,5,7],[9,6,5]])
add2=np.array([[4,1,3],[2,2,2],[0,5,3]])
total=np.add(add1,add2)
print(total)

[[ 6  4  7]
 [ 5  7  9]
 [ 9 11  8]]


Matrix subtraction


In [7]:
sub1=np.array([[2,3,4],[3,5,7],[9,6,5]])
sub2=np.array([[4,1,3],[2,2,2],[0,5,3]])
dif=np.subtract(sub1,sub2)
print(dif)

[[-2  2  1]
 [ 1  3  5]
 [ 9  1  2]]


Matrix multiplication


In [8]:
mat1=np.array([[2,3,4],[5,6,7],[9,6,5]])
mat2=np.array([[4,1,3],[2,2,2],[0,5,3]])
mat=np.matmul(mat1,mat2)
print(mat)

[[14 28 24]
 [32 52 48]
 [48 46 54]]


In [9]:
mat1=np.array([[2,3,4],[5,6,7],[9,6,5]])
mat2=np.array([[4,1,3],[2,2,2],[0,5,3]])
mat=np.dot(mat1,mat2)
print(mat)

[[14 28 24]
 [32 52 48]
 [48 46 54]]


Matrix transpose


In [12]:
tr=np.array([[2,3,4],
             [5,6,7],
             [9,6,5]])
transpose=np.transpose(tr)
print(transpose)

[[2 5 9]
 [3 6 6]
 [4 7 5]]
